spring:
  application:
    name: spring-boot-web

knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-home-custom: true
    home-custom-location: classpath:markdown/home.md
    home-custom-path: classpath:markdown/home.md
# ??????
#  basic:
#    enable: true
#    password: admin
#    username: admin
#    include: document,swagger
