spring:
  application:
    name: spring-boot-web
  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-web?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfileInMultiQueries=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&allowLoadLocalInfile=true&allowLocalInfileInMultiQueries=true&allowLoadLocalInfile=true&allowLocalInfileInMultiQueries=true&allowUrlInLocalInfile=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
knife4j:
  enable: true
  setting:
    language: zh-CN
